### PR TITLE
exclamation mark → invisible separator for tagging

### PR DESCRIPTION
**Pull request by Qwerty-Space**

### CODE REVIEW

**Comment by tnjd** [comment]
nah i like the exclamation marks

**Comment by Qwerty-Space** [comment]
The exclamation mark is still there
But it's basically just an invisible link now

**Comment by JuanPotato** [comment]
Yeah, but having multiple ! is cool because you can visually see how many people and who. I'm keeping it the way it is.

**Comment by Qwerty-Space** [comment]
Fair enough

**Pull request closed without merging**
