### PR TITLE
accept multiple words for member names

### PR DESCRIPTION
**Pull request by tnjd**

### CODE REVIEW

**Comment by JuanPotato** [comment]
Wouldnt work because the member name is what becomes used as the class name lol.

**Comment by tnjd** [comment]
well that's not ideal

**Comment by JuanPotato** [comment]
Yep

**Comment by tnjd** [comment]
what if we did a CamelCase conversion for the internal use, or used the tag for the class name

**Comment by JuanPotato** [comment]
Whatever we need to do, we're going to need to figure out some form of migration.

**Comment by tnjd** [comment]
so, use tag for class name, manual migration, delete the test groups?

**Comment by JuanPotato** [comment]
I guess so

**Comment by tnjd** [comment]
since we now know that class names can have whitespace, can this go through

**Comment by JuanPotato** [comment]
Yes

**Pull request merged**
